SELECT ProjectName, ProjectID, Budget FROM PROJECTS;

SELECT DISTINCT ProjectID FROM PROJECTS;

SELECT * FROM PROJECTS
WHERE Budget > 0;

SELECT * FROM PROJECTS
WHERE Budget > 0 AND Budget < 75001;

SELECT * FROM PROJECTS
WHERE Budget IN (0, 75001);

SELECT * FROM PROJECTS
WHERE Budget BETWEEN 0 AND 100001;

SELECT * FROM PROJECTS
WHERE ProjectName LIKE 'Project%';

SELECT * FROM PROJECTS
WHERE ProjectName IS NULL;

SELECT * FROM PROJECTS
WHERE ProjectName IS NOT NULL;